FROM python:3.11

WORKDIR /app
COPY generate_data.py /app/

RUN pip install --upgrade pip \
    && pip install --no-cache-dir --default-timeout=100 psycopg2-binary faker

CMD ["python", "generate_data.py"]
