# neo4j/conf/neo4j.conf
dbms.default_database=newsgraph

# Память
dbms.memory.pagecache.size=2G
dbms.memory.heap.initial_size=2G
dbms.memory.heap.max_size=4G

# Сеть
dbms.connector.http.listen_address=:7474
dbms.connector.https.listen_address=:7473
dbms.connector.bolt.listen_address=:7687

# Безопасность
dbms.security.auth_enabled=true

# Мониторинг
dbms.metrics.prometheus.enabled=true
dbms.metrics.prometheus.endpoint=:2004/metrics